version: "3.9"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbvolume:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile.rails
    volumes:
      - ./:/app
      - bundle:/bundle
    ports:
      - "3009:3000"
    command: bundle exec rails server -b 0.0.0.0
    entrypoint:
      - ./entrypoints/docker-entrypoint.sh
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  dbvolume:
  bundle:
