default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>
  user: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  timeout: 1000

development:
  <<: *default
  database: lunch_matcher_development
test:
  <<: *default
  database: lunch_matcher_test

production:
  <<: *default
  database: lunch_matcher_production
  username: lunch_matcher
  password: <%= ENV["LUNCH_MATCHER_DATABASE_PASSWORD"] %>
